name: on_push_to_master.yaml>> task - validate commit on master
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions
        uses: actions/checkout@v2
      
      - name: Skip if files not changed
        uses: ./.github/mini_flows/s1_mandatory_filechanges      
